/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/roof.gltf 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function Roof(props) {
  const { nodes, materials } = useGLTF('/roof.gltf');
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[1.125, 3, 1]}>
        <mesh
          geometry={nodes.Lodge_20x190x1000_bevel.geometry}
          material={materials['wood.001']}
        />
        <mesh
          geometry={nodes.Lodge_20x190x1000_bevel_1.geometry}
          material={materials.asphalt}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <mesh
          geometry={nodes.balk_corner013.geometry}
          material={materials['wood.016']}
        />
        <mesh
          geometry={nodes.balk_corner013_1.geometry}
          material={materials['wood.017']}
        />
        <mesh
          geometry={nodes.balk_corner013_2.geometry}
          material={materials['wood.023']}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, Math.PI]}>
        <mesh
          geometry={nodes.balk_corner015.geometry}
          material={materials['wood.018']}
        />
        <mesh
          geometry={nodes.balk_corner015_1.geometry}
          material={materials['wood.015']}
        />
        <mesh
          geometry={nodes.balk_corner015_2.geometry}
          material={materials['wood.023']}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, Math.PI]}>
        <mesh
          geometry={nodes.balk_corner016.geometry}
          material={materials['wood.019']}
        />
        <mesh
          geometry={nodes.balk_corner016_1.geometry}
          material={materials['wood.023']}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, Math.PI]}>
        <mesh
          geometry={nodes.balk_corner017.geometry}
          material={materials['wood.020']}
        />
        <mesh
          geometry={nodes.balk_corner017_1.geometry}
          material={materials['wood.023']}
        />
      </group>
      <mesh
        geometry={nodes.col_corner001.geometry}
        material={materials['wood.023']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.balk_150x150x2200007.geometry}
          material={materials['wood.023']}
        />
        <mesh
          geometry={nodes.balk_150x150x2200007_1.geometry}
          material={materials['wood.022']}
        />
        <mesh
          geometry={nodes.balk_150x150x2200007_2.geometry}
          material={materials['wood.021']}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[5, 1, 1]}>
        <mesh
          geometry={nodes.lodge_150x50x1000002.geometry}
          material={materials['wood.001']}
        />
        <mesh
          geometry={nodes.lodge_150x50x1000002_1.geometry}
          material={materials.M_RoofEdge_1}
        />
        <mesh
          geometry={nodes.lodge_150x50x1000002_2.geometry}
          material={materials['wood.002']}
        />
        <mesh
          geometry={nodes.lodge_150x50x1000002_3.geometry}
          material={materials['wood.012']}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[5, 1, 1]}>
        <mesh
          geometry={nodes.lodge_150x50x1000004.geometry}
          material={materials['wood.001']}
        />
        <mesh
          geometry={nodes.lodge_150x50x1000004_1.geometry}
          material={materials.M_RoofEdge_1}
        />
        <mesh
          geometry={nodes.lodge_150x50x1000004_2.geometry}
          material={materials['wood.002']}
        />
        <mesh
          geometry={nodes.lodge_150x50x1000004_3.geometry}
          material={materials['wood.011']}
        />
      </group>
      <mesh
        geometry={nodes.lodge_length003.geometry}
        material={materials['wood.001']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[5, 1, 1]}
      />
      <mesh
        geometry={nodes.lodge_length004.geometry}
        material={materials['wood.001']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[5, 1, 1]}
      />
      <mesh
        geometry={nodes.lodge_width.geometry}
        material={materials['wood.001']}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[3, 1, 1]}
      />
      <group rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[3, 1, 1]}>
        <mesh
          geometry={nodes.lodge_150x50x1000007.geometry}
          material={materials['wood.001']}
        />
        <mesh
          geometry={nodes.lodge_150x50x1000007_1.geometry}
          material={materials['wood.014']}
        />
        <mesh
          geometry={nodes.lodge_150x50x1000007_2.geometry}
          material={materials.M_RoofEdge_1}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[3, 1, 1]}>
        <mesh
          geometry={nodes.lodge_150x50x1000008.geometry}
          material={materials['wood.001']}
        />
        <mesh
          geometry={nodes.lodge_150x50x1000008_1.geometry}
          material={materials['wood.013']}
        />
        <mesh
          geometry={nodes.lodge_150x50x1000008_2.geometry}
          material={materials.M_RoofEdge_1}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/roof.gltf');
