/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/roof.gltf 
*/

import { useGLTF } from '@react-three/drei';
import { useEffect, useState } from 'react';
import { useConfigurator } from '../context/Configurator';

export function Roof(props) {
  const { nodes, materials } = useGLTF('/roof.gltf');
  const { roofLength, roofWidth } = useConfigurator();
  const [widthPosition, setWidthPosition] = useState(0);
  const [lengthPosition, setLengthPosition] = useState(0);

  const positions = {
    widthPositions: [0, 0.52, 1.07, 1.6, 2.13, 2.65, 3.19, 3.73],
    lengthPositions: [-1, -0.5, 0, 0.5, 1.05, 1.55, 2.05, 2.55],
  };

  useEffect(() => {
    setWidthPosition(positions.widthPositions[roofWidth - 3]);
    setLengthPosition(positions.lengthPositions[roofLength - 3]);
  }, [roofWidth, roofLength]);

  return (
    <group {...props} dispose={null}>
      {/* top */}
      <group
        rotation={[Math.PI / 2, 0, 0]}
        scale={[roofLength * 0.23, roofWidth * 1.05, 1]}
      >
        <mesh
          geometry={nodes.Lodge_20x190x1000_bevel.geometry}
          material={materials['wood.001']}
          castShadow
        />
        <mesh
          geometry={nodes.Lodge_20x190x1000_bevel_1.geometry}
          material={materials.asphalt}
          castShadow
        />
      </group>
      {/* cols */}
      <group
        position={[lengthPosition, 0, -widthPosition]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      >
        <mesh
          geometry={nodes.balk_corner013.geometry}
          material={materials['wood.016']}
          castShadow
        />
        <mesh
          geometry={nodes.balk_corner013_1.geometry}
          material={materials['wood.017']}
          castShadow
        />
        <mesh
          geometry={nodes.balk_corner013_2.geometry}
          material={materials['wood.023']}
          castShadow
        />
      </group>
      <group
        position={[lengthPosition, 0, widthPosition]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      >
        <mesh
          geometry={nodes.balk_corner015.geometry}
          material={materials['wood.018']}
          castShadow
        />
        <mesh
          geometry={nodes.balk_corner015_1.geometry}
          material={materials['wood.015']}
          castShadow
        />
        <mesh
          geometry={nodes.balk_corner015_2.geometry}
          material={materials['wood.023']}
          castShadow
        />
      </group>
      {/* central cols (length side) */}
      {roofLength >= 5 && (
        <>
          <group
            position={
              roofLength >= 8
                ? [roofLength === 10 ? 2.5 : 1.5, 0, widthPosition]
                : [0, 0, widthPosition]
            }
            rotation={[Math.PI / 2, 0, Math.PI]}
          >
            <mesh
              geometry={nodes.balk_corner016.geometry}
              material={materials['wood.019']}
              castShadow
            />
            <mesh
              geometry={nodes.balk_corner016_1.geometry}
              material={materials['wood.023']}
              castShadow
            />
          </group>
          <group
            position={
              roofLength >= 8
                ? [roofLength === 10 ? 2.5 : 1.5, 0, -widthPosition]
                : [0, 0, -widthPosition]
            }
            rotation={[Math.PI / 2, 0, Math.PI]}
          >
            <mesh
              geometry={nodes.balk_corner017.geometry}
              material={materials['wood.020']}
              castShadow
            />
            <mesh
              geometry={nodes.balk_corner017_1.geometry}
              material={materials['wood.023']}
              castShadow
            />
          </group>

          {roofLength >= 8 && (
            <>
              <group
                position={[roofLength === 10 ? -2.5 : -1.5, 0, widthPosition]}
                rotation={[Math.PI / 2, 0, Math.PI]}
              >
                <mesh
                  geometry={nodes.balk_corner016.geometry}
                  material={materials['wood.019']}
                  castShadow
                />
                <mesh
                  geometry={nodes.balk_corner016_1.geometry}
                  material={materials['wood.023']}
                  castShadow
                />
              </group>
              <group
                position={[roofLength === 10 ? -2.5 : -1.5, 0, -widthPosition]}
                rotation={[Math.PI / 2, 0, Math.PI]}
              >
                <mesh
                  geometry={nodes.balk_corner017.geometry}
                  material={materials['wood.020']}
                  castShadow
                />
                <mesh
                  geometry={nodes.balk_corner017_1.geometry}
                  material={materials['wood.023']}
                  castShadow
                />
              </group>
            </>
          )}

          {roofLength === 10 && (
            <>
              <group
                position={[0, 0, widthPosition]}
                rotation={[Math.PI / 2, 0, Math.PI]}
              >
                <mesh
                  geometry={nodes.balk_corner016.geometry}
                  material={materials['wood.019']}
                  castShadow
                />
                <mesh
                  geometry={nodes.balk_corner016_1.geometry}
                  material={materials['wood.023']}
                  castShadow
                />
              </group>
              <group
                position={[0, 0, -widthPosition]}
                rotation={[Math.PI / 2, 0, Math.PI]}
              >
                <mesh
                  geometry={nodes.balk_corner017.geometry}
                  material={materials['wood.020']}
                  castShadow
                />
                <mesh
                  geometry={nodes.balk_corner017_1.geometry}
                  material={materials['wood.023']}
                  castShadow
                />
              </group>
            </>
          )}
        </>
      )}

      {/* central cols (width side) */}
      {roofWidth >= 5 && (
        <>
          <group
            position={
              roofWidth >= 8
                ? [-3.6 - lengthPosition, 0, roofWidth === 10 ? 2.5 : 1.5]
                : [-3.6 - lengthPosition, 0, 0]
            }
            rotation={[Math.PI / 2, 0, Math.PI / 2]}
          >
            <mesh
              geometry={nodes.balk_corner016.geometry}
              material={materials['wood.019']}
              castShadow
            />
            <mesh
              geometry={nodes.balk_corner016_1.geometry}
              material={materials['wood.023']}
              castShadow
            />
          </group>
          <group
            position={
              roofWidth >= 8
                ? [3.6 + lengthPosition, 0, roofWidth === 10 ? 2.5 : 1.5]
                : [3.6 + lengthPosition, 0, 0]
            }
            rotation={[Math.PI / 2, 0, Math.PI / 2]}
          >
            <mesh
              geometry={nodes.balk_corner017.geometry}
              material={materials['wood.020']}
              castShadow
            />
            <mesh
              geometry={nodes.balk_corner017_1.geometry}
              material={materials['wood.023']}
              castShadow
            />
          </group>

          {roofWidth >= 8 && (
            <>
              <group
                position={
                  roofWidth >= 8
                    ? [-3.6 - lengthPosition, 0, roofWidth === 10 ? -2.5 : -1.5]
                    : [-3.6 - lengthPosition, 0, 0]
                }
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
              >
                <mesh
                  geometry={nodes.balk_corner016.geometry}
                  material={materials['wood.019']}
                  castShadow
                />
                <mesh
                  geometry={nodes.balk_corner016_1.geometry}
                  material={materials['wood.023']}
                  castShadow
                />
              </group>
              <group
                position={
                  roofWidth >= 8
                    ? [3.6 + lengthPosition, 0, roofWidth === 10 ? -2.5 : -1.5]
                    : [3.6 + lengthPosition, 0, 0]
                }
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
              >
                <mesh
                  geometry={nodes.balk_corner017.geometry}
                  material={materials['wood.020']}
                  castShadow
                />
                <mesh
                  geometry={nodes.balk_corner017_1.geometry}
                  material={materials['wood.023']}
                  castShadow
                />
              </group>
            </>
          )}

          {roofWidth >= 10 && (
            <>
              <group
                position={[-3.6 - lengthPosition, 0, 0]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
              >
                <mesh
                  geometry={nodes.balk_corner016.geometry}
                  material={materials['wood.019']}
                  castShadow
                />
                <mesh
                  geometry={nodes.balk_corner016_1.geometry}
                  material={materials['wood.023']}
                  castShadow
                />
              </group>
              <group
                position={[3.6 + lengthPosition, 0, 0]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
              >
                <mesh
                  geometry={nodes.balk_corner017.geometry}
                  material={materials['wood.020']}
                  castShadow
                />
                <mesh
                  geometry={nodes.balk_corner017_1.geometry}
                  material={materials['wood.023']}
                  castShadow
                />
              </group>
            </>
          )}
        </>
      )}

      <mesh
        geometry={nodes.col_corner001.geometry}
        material={materials['wood.023']}
        rotation={[Math.PI / 2, 0, 0]}
        position={[-lengthPosition, 0, widthPosition]}
        castShadow
      />
      <group
        rotation={[Math.PI / 2, 0, 0]}
        position={[-lengthPosition, 0, -widthPosition]}
      >
        <mesh
          geometry={nodes.balk_150x150x2200007.geometry}
          material={materials['wood.023']}
          castShadow
        />
        <mesh
          geometry={nodes.balk_150x150x2200007_1.geometry}
          material={materials['wood.022']}
          castShadow
        />
        <mesh
          geometry={nodes.balk_150x150x2200007_2.geometry}
          material={materials['wood.021']}
          castShadow
        />
      </group>
      {/* right side */}
      <group
        position={[0, 0, -widthPosition]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[roofLength, 1, 1]}
      >
        <mesh
          geometry={nodes.lodge_150x50x1000002.geometry}
          material={materials['wood.001']}
          castShadow
        />
        <mesh
          geometry={nodes.lodge_150x50x1000002_1.geometry}
          material={materials.M_RoofEdge_1}
          castShadow
        />
        <mesh
          geometry={nodes.lodge_150x50x1000002_2.geometry}
          material={materials['wood.002']}
          castShadow
        />
        <mesh
          geometry={nodes.lodge_150x50x1000002_3.geometry}
          material={materials['wood.012']}
          castShadow
        />
      </group>
      {/* left side */}
      <group
        position={[0, 0, widthPosition]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[roofLength, 1, 1]}
      >
        <mesh
          geometry={nodes.lodge_150x50x1000004.geometry}
          material={materials['wood.001']}
          castShadow
        />
        <mesh
          geometry={nodes.lodge_150x50x1000004_1.geometry}
          material={materials.M_RoofEdge_1}
          castShadow
        />
        <mesh
          geometry={nodes.lodge_150x50x1000004_2.geometry}
          material={materials['wood.002']}
          castShadow
        />
        <mesh
          geometry={nodes.lodge_150x50x1000004_3.geometry}
          material={materials['wood.011']}
          castShadow
        />
      </group>
      {/* left small l */}
      <mesh
        position={[0, 0, -widthPosition]}
        geometry={nodes.lodge_length003.geometry}
        material={materials['wood.001']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[roofLength, 1, 1]}
        castShadow
      />
      {/* right small l */}
      <mesh
        position={[0, 0, -widthPosition]}
        geometry={nodes.lodge_length004.geometry}
        material={materials['wood.001']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[roofLength, 1, 1]}
        castShadow
      />
      {/* left small l */}
      {roofWidth >= 5 && (
        <>
          <mesh
            position={[0, 0, -widthPosition + 2]}
            geometry={nodes.lodge_length003.geometry}
            material={materials['wood.001']}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[roofLength, 1, 1]}
            castShadow
          />
          {/* right small l */}
          <mesh
            position={[0, 0, -widthPosition + 2]}
            geometry={nodes.lodge_length004.geometry}
            material={materials['wood.001']}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[roofLength, 1, 1]}
            castShadow
          />
          {roofWidth >= 7 && (
            <>
              <mesh
                position={[0, 0, widthPosition]}
                geometry={nodes.lodge_length003.geometry}
                material={materials['wood.001']}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[roofLength, 1, 1]}
                castShadow
              />
              {/* right small l */}
              <mesh
                position={[0, 0, widthPosition]}
                geometry={nodes.lodge_length004.geometry}
                material={materials['wood.001']}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[roofLength, 1, 1]}
                castShadow
              />
              <mesh
                position={[0, 0, widthPosition - 2]}
                geometry={nodes.lodge_length003.geometry}
                material={materials['wood.001']}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[roofLength, 1, 1]}
                castShadow
              />
              {/* right small l */}
              <mesh
                position={[0, 0, widthPosition - 2]}
                geometry={nodes.lodge_length004.geometry}
                material={materials['wood.001']}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[roofLength, 1, 1]}
                castShadow
              />
            </>
          )}
        </>
      )}
      {/* central w */}
      <mesh
        position={roofLength < 5 ? [0, 0, 0] : [lengthPosition, 0, 0]}
        geometry={nodes.lodge_width.geometry}
        material={materials['wood.001']}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={roofLength < 5 ? [roofWidth, 0.75, 1] : [roofWidth, 1, 1]}
        castShadow
      />
      {roofLength > 5 && (
        <mesh
          position={[-lengthPosition, 0, 0]}
          geometry={nodes.lodge_width.geometry}
          material={materials['wood.001']}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[roofWidth, 1, 1]}
          castShadow
        />
      )}
      {/* right w */}
      <group
        position={[-lengthPosition, 0, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[roofWidth, 1, 1]}
      >
        <mesh
          geometry={nodes.lodge_150x50x1000007.geometry}
          material={materials['wood.001']}
          castShadow
        />
        <mesh
          geometry={nodes.lodge_150x50x1000007_1.geometry}
          material={materials['wood.014']}
          castShadow
        />
        <mesh
          geometry={nodes.lodge_150x50x1000007_2.geometry}
          material={materials.M_RoofEdge_1}
          castShadow
        />
      </group>
      {/* left w */}
      <group
        position={[lengthPosition, 0, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[roofWidth, 1, 1]}
      >
        <mesh
          geometry={nodes.lodge_150x50x1000008.geometry}
          material={materials['wood.001']}
          castShadow
        />
        <mesh
          geometry={nodes.lodge_150x50x1000008_1.geometry}
          material={materials['wood.013']}
          castShadow
        />
        <mesh
          geometry={nodes.lodge_150x50x1000008_2.geometry}
          material={materials.M_RoofEdge_1}
          castShadow
        />
      </group>
    </group>
  );
}

useGLTF.preload('/roof.gltf');
